### ISSUE TITLE
ethernet-container-pac not writable

### ISSUE THREAD

**Issue by michbin** [openBackhaul/ethernetContainer#16]
_ethernet-container-configuration_ does not seem to be configurable. I received the following error message while trying to configure some of its attributes:
```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>unknown-element</error-tag>
    <error-severity>error</error-severity>
    <error-app-tag>not-writable</error-app-tag>
    <error-path xmlns:ethernet-container="urn:onf:yang:ethernet-container-2-0" xmlns:core-model="urn:onf:yang:core-model-1-4">
    /rpc/edit-config/config/core-model:control-construct/core-model:logical-termination-point[core-model:uuid='ETH/2134647012']/core-model:layer-protocol[core-model:local-id='2134647012']/ethernet-container:ethernet-container-pac
  </error-path>
    <error-message xml:lang="en">object is not writable</error-message>
    <error-info>
      <bad-element>ethernet-container-pac</bad-element>
    </error-info>
  </rpc-error>
</rpc-reply>

```
The reason is that _ethernet-container-pac_ is set to `config false` but _ethernet-container-configuration_ is not set to `config true` so it inherits not being configurable.

**Comment by niloda** [comment]
It seems to be due to ethernet-container-lp-spec which is tagged with "config false" so each beneath attribute is not configurable.

grouping ethernet-container-lp-spec {
    container ethernet-container-pac {
      **config false;**
      uses ethernet-container-pac;
      description
        "none";
    }
    description
      "none";
  }

**Comment by openBackhaul** [comment]
EthernetContainerLpSpec::_ethernetContainer_Pac has been made IsReadOnly==false.

**Comment by openBackhaul** [comment]
UML and YANG have already been corrected.
Existing implementations are basing on the corrected YANG.

**Proposal to the 5G-xhaul call on 21st of April:**
Just closing the issue
