### ISSUE TITLE
supported-header-compression-kind-list requires min-elements equal to 1

### ISSUE THREAD

**Issue by niloda** [openBackhaul/ethernetContainer#17]
supported-header-compression-kind-list must have al least an element otherwise the MUST condition of header-compression-kind will fails.

**Comment by openBackhaul** [comment]
Multiplicity of EthernetContainerCapability::_supportedHeaderCompressionKindList has been changed to 1..*   .

**Comment by michbin** [comment]
> 
> 
> supported-header-compression-kind-list must have al least an element otherwise the MUST condition of header-compression-kind will fails.

What was the problem? Did it cause a compile error?

What is the expected behavior if header compression is not supported?

**Comment by openBackhaul** [comment]
Solution:
One instance of HeaderCompressionKind that has to be created according to solution in issue#29 and to be referenced as a default.

**Comment by openBackhaul** [comment]
UML and YANG have already been corrected.
Existing implementations are basing on the corrected YANG.

**Proposal to the 5G-xhaul call on 21st of April:**
Just closing the issue
