### ISSUE TITLE
Bundling attributes for Ethernet ports

### ISSUE THREAD

**Issue by michbin** [openBackhaul/ethernetContainer#23]
Bundling attributes (_bundling-is-avail_, _bundling-is-on_, _bundling-is-up_) are not applicable to Ethernet Container objects which represent Ethernet ports. 
The model should define how these attributes should be treated for Ethernet ports.

**Comment by openBackhaul** [comment]
Don't see any reason to treat them different than usual.
If the Ethernet port doesn't support bundling: bundling-is-avail==false and bundling-is-on and bundling-is-up are sticking with their default values.

**Comment by openBackhaul** [comment]
Based on the latest ideas about distinguishing administrative and operational configuration:
In case the EthernetContainer would be client to a WireInterface:

- EthernetContainerCapability::bundling-is-avail==false
- EthernetContainerConfiguration::bundling-is-on would not be represented
- EthernetContainerStatus::bundling-is-on==false
- (EthernetContainerStatus::bundling-is-up would be deleted from the modeling)

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 16th of June 2021**
- Comment of EthernetContainerConfiguration::bundlingIsOn to be changed from "802.3 according to 30.11.1.1.5 aPAFAdminState and 45.2.3.26.3 PAF enable. 1 = Algorithm for bundling Ethernet segments is activated (, even if only a single Structure would be associated)." to "...bundling Ethernet segments on AirInterfaces is activated ...".
- Comment of EthernetContainerStatus::bundlingIsUp to be changed from "802.3 and ITU-T Rec. G.998.3 Appendix II aGroupStatus. 1 = Algorithm for bundling Ethernet segments is operative (, even if only a single Structure would be associated)." to "...bundling Ethernet segments on AirInterfaces is operative ...".

**Comment by openBackhaul** [comment]
Fixed with EthernetContainer_2.0.0-tsp.220405.1755.
