### ISSUE TITLE
time-of-latest-change: wrong type

### ISSUE THREAD

**Issue by michbin** [openBackhaul/ethernetContainer#25]
The following time stamps have type string but should have type `yang:date-and-time`:

- `ethernet-container-current-problems/time-of-latest-change`
- `ethernet-container-historical-performances/time-of-latest-change`

**Comment by openBackhaul** [comment]
In the UML it's fine.
In the YANG reference it's also fine (no change required).

**Comment by openBackhaul** [comment]
Both data types are fine in UML and YANG.
Existing implementations are basing on the corrected YANG.

**Proposal to the 5G-xhaul call on 21st of April:**
Just closing the issue
