### ISSUE TITLE
Multiplicity of _supportedHeaderCompressionKindList = 1, but headerCompressionName undefined

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ethernetContainer#26]
Minimum instances of _supportedHeaderCompressionKindList attribute is 1. 
But default values cannot be associated with key attribute values like headerCompressionName.

For assuring a harmonized implementation for hardware that doesn't support header compression:
The following comment shall be added to headerCompressionName attribute: "In case hardware does not support header compression, one instance with headerCompressionName="None" shall be instantiated.

**Comment by michbin** [comment]
Isn't header compression only applied to traffic over an air interface?
Should the single entry described above really be reported if the underlying server LTP is a wire interface?

**Comment by openBackhaul** [comment]
**Solution:**
There will be no prescribed default value for header-compression-name.
The instance of HeaderCompressionKind that has been created according to solution in issue#29 has to be referenced as a default.

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul-call on 12th of May 2021:**
The comment "In case hardware does not support header compression, one instance with headerCompressionName="None" shall be instantiated." to be deleted from the HeaderCompressionKind::headerCompressionName attribute.

**Comment by openBackhaul** [comment]
Fixed with EthernetContainer_2.0.0-tsp.220405.1755.
