### ISSUE TITLE
Allowed queue depth values to be declared as capability

### ISSUE THREAD

**Issue by niloda** [openBackhaul/ethernetContainer#28]
Some hardware can configure the depth of an egress queue to a value choose within a defined list of permitted values. This means that the depth cannot be freely set to a value in the range 0..max-queue-depth. The current model does not allow a user to be aware about the permitted values.

Proposed solution
A list of integer values can be added to ethernet-container-capability to be filled with the permitted values of queue depth. In case the hardware supports any value between 0 and max-queue-depth, this list can be filled with a subset of  permitted values. In case the queue depth cannot be configured, the list should contain only the value -1. The attribute max-queue-depth can be removed from ethernet-container-capability.

**Comment by demx8as6** [comment]
**Info:** All api providers and consumers (hardware and software vendors) are ask to check if the proposed solution works and can be implemented. If so, it would be the preferred solution.


**Just for documentation**: how the issues could be solved too, but would need tooling enhancements, therefore it is not the preferred solution. 

[ethernet-container-2-0@2020-04-21.yang.txt](https://github.com/openBackhaul/ethernetContainer/files/4509390/ethernet-container-2-0%402020-04-21.yang.txt)
[ethernet-container-2-0@2020-04-21.yang.tree.txt](https://github.com/openBackhaul/ethernetContainer/files/4509393/ethernet-container-2-0%402020-04-21.yang.tree.txt)
![proposal-for-eht-container-issue28](https://user-images.githubusercontent.com/9154981/79856631-dcd90a80-83cc-11ea-98a3-4633335c5e44.png)

**Comment by michbin** [comment]
It should be feasible to implement the proposal.
However, we should keep in mind that the list of supported values can become quite large. I know of one example with at least 120 values.

The most general solution would be a union (simplified Yang syntax):
```
  choice available-queue-depth
    case range
      leaf min-value
      leaf max-value
      leaf step-width
    case set
      leaf-list supported-value-list
```

I am not sure whether we would like to spend the necessary effort.

**Comment by demx8as6** [comment]
**Solution:**

Note: the following description and wording uses terms and notations from ethernet-container-2-0.yang. The mapping to UML is made by UML modelers. Results after UML to YANG translations will look as described below.

In ethernet-container-capabilities the attribute (or leaf) "max-queue-depth" is replaced by a leaf-list "supported-queue-depth".

The min-elements statement gets the value 1 (UML multiplicity: 1..*), to force the implementation to express also in cases that the configuration of "queue-depth" is not supported, to express that only the default-value -1 is supported. As a consequence the attribute (or leaf) "queue-depth-configuration-is-avail" will be removed. The description in ethernet-configuration for lead "queue-depth" must be adopted.

The description of the leaf-list "supported-queue-depth" must explain the following information for implementation on device, mediator and SDN-app level.

- The "supported-queue-depth" list must list supported configuration values by the NetConf server.

- It is possible that more values are supported for configuration between the minimum and maximum value of the "supported-queue-depth", than listed in the "supported-queue-depth" list. As a consequence in ethernet-configuration the "queue-depth" attribute (or leaf) must not have a yang must statement referencing values between the minimum and maximum value of the "supported-queue-depth".

- If a value is configured, which is not in the "supported-queue-depth", it is a decision by the device-software or mediator-software how to handle the situation. It is preferred to map the configuration value to a value within the "supported-queue-depth".

- It is highly recommended to SDN-application development to only configure values for "queue-depth" which are listed in "supported-queue-depth".

- Values lower than the minimum value of the "supported-queue-depth" must not be configured.

- Values greater than the minimum value of the "supported-queue-depth" must not be configured.

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul-call on 12th of May 2021:**
(same as described as solution above)
Note: the following description and wording uses terms and notations from ethernet-container-2-0.yang. The mapping to UML is made by UML modelers. Results after UML to YANG translations will look as described below.

The attribute (or leaf) "max-queue-depth" is replaced by a leaf-list "supported-queue-depth-list" in ethernet-container-capabilities, respectively the AvailableQueueType datatype in the UML.

The min-elements statement gets the value 1 (UML multiplicity: 1..*), to force the interface implementation to express the default-value -1 in case configuring the buffer size would not be supported by the hardware. As a consequence the attribute (or leaf) "queue-depth-configuration-is-avail" will be removed. The description in ethernet-configuration for lead "queue-depth" must be adopted.

The description of the leaf-list "supported-queue-depth-list" must explain the following information for implementation on device, mediator and SDN-app level.

- The "supported-queue-depth-list" must exclusively contain values, which are actually configurable at the hardware (except of the default value -1, in case buffer size cannot be configured at all).

 - The values listed in "supported-queue-depth-list" might be all or a subset of values actually configurable at the hardware. To allow configuring the device according to its full capabilities, the values entered into the "queue-depth" attribute (or leaf) in the ethernet-configuration are not limited to the ones stated in "supported-queue-depth-list" (YANG must not contain a MUST statement referencing the values of the "supported-queue-depth-list " capability attribute.)

- If a value, which is supported by the hardware, but not listed in the "supported-queue-depth-list", would be tried to be configured, the device-software or mediator-software shall successfully validate (and operate) it.

- If a value, which is not supported by the hardware, would be tried to be configured, the device-software or mediator-software might implementation specifically react . It could either respond with operation failed and ...Configuration value out of range of hardware capabilities... or it could map the sent configuration value on the closest value, which is actually supported by the hardware. Vendors are free to chose according to the existing capabilities of their devices.

- Configuration attempts with values lower than the minimum value or higher than the maximum value of the "supported-queue-depth-list" must be answered with the operation failed and ...Configuration value out of range of hardware capabilities...

**Comment by openBackhaul** [comment]
Fixed with EthernetContainer_2.0.0-tsp.220405.1755.
