### ISSUE TITLE
txEthernetBytesMaxM is not supported by hardware implementations

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ethernetContainer#33]
The txEthernetBytesMaxM attribute in the ContainerPerformanceType is not supported by any hardware implementation.

**Proposal:**
The txEthernetBytesMaxM attribute in the ContainerPerformanceType is to be removed from the information model.

**Comment by demx8as6** [comment]
To be decided in ONF 5G-xHaul call 2021-06-30.

**Comment by openBackhaul** [comment]
**Decision made on the 5G-xhaul-call on 30th of June 2021:**
The txEthernetBytesMaxM attribute in the ContainerPerformanceType is to be removed from the information model.

**Comment by openBackhaul** [comment]
Fixed with EthernetContainer_2.0.0-tsp.220405.1755.
