### ISSUE TITLE
Performance Counters to be complemented

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ethernetContainer#34]
There are values that are already available in the Status class as statistics values, which are required as performance counters, too.

**Proposal:**
The following attribute to be added to the ContainerPerformanceType datatype:
- totalBytesInput

**Comment by demx8as6** [comment]
Proposal:
The following attribute to be added to the ContainerPerformanceType datatype:

totalBytesInput

To be approved on 2021-06-30 - 5G xHaul call.

**Comment by openBackhaul** [comment]
**Decision made on the 5G-xhaul-call on 30th of June 2021:**
An ContainerPerformanceType::totalBytesInput attribute to be added.

**Comment by openBackhaul** [comment]
Fixed with EthernetContainer_2.0.0-tsp.220405.1755.
