### ISSUE TITLE
Naming of Performance Counters to be harmonized

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ethernetContainer#35]
Naming of Performance Counters should be harmonized with naming of Statistics and across the technology specific models.

**Proposal**
- txEthernetBytesSum to be renamed to totalBytesOutput
- txEthernetBytesMaxS to be renamed to maxBytesPerSecondOutput

**Comment by demx8as6** [comment]
To be decided in ONF 5G-xHaul call 2021-06-30.

**Comment by demx8as6** [comment]
To be approved on 2021-06-30 - 5G xHaul call.

**Comment by openBackhaul** [comment]
**Decision made on the 5G-xhaul-call on 30th of June 2021:**
- txEthernetBytesSum to be renamed to totalBytesOutput
- txEthernetBytesMaxS to be renamed to maxBytesPerSecondOutput

**Comment by openBackhaul** [comment]
Fixed with EthernetContainer_2.0.0-tsp.220405.1755.
