### ISSUE TITLE
queue-depth on device/switch level

### ISSUE THREAD

**Issue by niloda** [openBackhaul/ethernetContainer#36]
Some devices allow configuring the the queue-depth not per interface/queue, but per switch/device only. Current model do not support these kind of devices.

Requirement:
There should be the possibility to configure the depth for all the queues using a per switch/device profile choosen from a list of profile declared by the device.

Proposal:
Current technology-specific models do not provide a class that represents the device or switch. The core model provides the forwarding-domain to represent the switch. It should be discussed whether switch-level settings should be placed in a class that augments the forwarding-domain.

**Comment by openBackhaul** [comment]
**Decision on 5Gxhaul call on 3rd of June:**
Capability attributes are to be added for expressing, whether the device is supporting configuring
- queue depth
- dropping behavior
- wred profile
- scheduler kind
on an interface base.
Further on, an EthernetContainerFd shall be defined for holding the same attributes plus some similar Capability attributes for facilitating the configuring queue depth, dropping behavior,  wred profile and scheduler kind on an switch base.

**Next steps:**
Defining the Capability attributes, which are to be added to the EthernetContainer

**Comment by PrathibaJee** [comment]
As per [issue#28](https://github.com/openBackhaul/ethernetContainer/issues/28) , the attribute **queue-depth-configuration-is-avail** will not be required.
When a hardware do not support configuration of the buffer size , it can be expressed by representing -1 as the value for the attribute ethernet-container-capabilities/supported-queue-depth-list.

The following attributes shall be added to the EthernetContainerCapability class:
- EthernetContainerCapability::droppingBehaviorConfigurationIsAvail : Boolean [1] = false with comment "This attribute has to be set on 'true', if the dropping behavior can be configured individually at every interface".
- EthernetContainerCapability::wredProfileConfigurationIsAvail : Boolean [1] = false with comment "This attribute has to be set on 'true', if the WRED Profile can be configured individually at every interface".
- EthernetContainerCapability::schedulerKindConfigurationIsAvail : Boolean [1] = false with comment "This attribute has to be set on 'true', if the kind of scheduler can be configured individually at every interface".

The following attribute shall be deleted from the AvailableQueueType:
- AvailableQueueType::queueDepthConfigurationIsAvail

**Comment by demx8as6** [comment]
There is a "conflict" between issue #28 and issue #36.

The part in issue 36:
[...]
- EthernetContainerCapability::queueDepthConfigurationIsAvail : Boolean [1] = false with comment "This attribute has to be set on 'true', if the queue depth can be configured individually at every interface".
[...]
is not needed as it is redundant. 

Even so - we keep decision in issue 28 and 36 as is.

**Comment by openBackhaul** [comment]
Fixed with EthernetContainer_2.0.0-tsp.220405.1755.
