### ISSUE TITLE
queue-depth might have discrete value ranges

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ethernetContainer#41]
Devices might support only a subset of values between minimum and maximum value of the range.
PUT requests will fail when attempting to configure some value inside the range, but not coinciding with one of the supported values.

Potential solutions:
a) Capability attribute representing a list of allowed values (maybe subset of supported values)
b) Device/Mediator automatically choosing the closest value

(A similar problem (queue-depth) has been covered in issue#28 by choosing option a).
Option b) could be generic solution that avoids further Capability attributes.)

**Comment by krgaurav29** [comment]
Do we have any update on this Bug?

**Comment by openBackhaul** [comment]
This issue has been covered by the decision made in [issue #28](https://github.com/openBackhaul/ethernetContainer/issues/28).
