### ISSUE TITLE
Deleting unsupported performance attributes

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ethernetContainer#43]
It is proposed to remove a couple of performance and status attributes, which are not supported by any hardware we had under test so far.

**Proposal:**
The following attribute to be deleted from the modeling:
- ContainerPerformanceType::fec-corrected-blocks
- ContainerPerformanceType::fec-uncorrectable-blocks
- EthernetContainerStatus::forwarded-bytes-input
- EthernetContainerStatus::forwarded-bytes-output

**Comment by openBackhaul** [comment]
Decision at the 5G-xhaul call on Tuesday 2nd of September 2020:

The following attributes shall be deleted from the modeling:
ContainerPerformanceType::fec-corrected-blocks
ContainerPerformanceType::fec-uncorrectable-blocks
EthernetContainerStatus::forwarded-bytes-input
EthernetContainerStatus::forwarded-bytes-output

Updating UML and YANG required.

**Comment by demx8as6** [comment]
Proposal:
The following attribute to be deleted from the modeling:

ContainerPerformanceType::fec-corrected-blocks
ContainerPerformanceType::fec-uncorrectable-blocks
EthernetContainerStatus::forwarded-bytes-input
EthernetContainerStatus::forwarded-bytes-output

To be approved on 2021-06-30 - 5G xHaul call.

**Comment by openBackhaul** [comment]
**Decision made on the 5G-xhaul-call on 30th of June 2021:**
The following attribute to be deleted from the modeling:
- ContainerPerformanceType::fec-corrected-blocks
- ContainerPerformanceType::fec-uncorrectable-blocks
- EthernetContainerStatus::forwarded-bytes-input
- EthernetContainerStatus::forwarded-bytes-output

**Comment by openBackhaul** [comment]
Fixed with EthernetContainer_2.0.0-tsp.220405.1755.
