### ISSUE TITLE
Are there RMON counters to be moved from MacInterface to EthernetContainer?

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ethernetContainer#45]

**Comment by demx8as6** [comment]
Email send to Andreas

Spreadsheet not found (yet):

https://wiki.opennetworking.org/dosearchsite.action?cql=siteSearch%20~%20%22RMON%22%20AND%20type%20in%20(%22space%22%2C%22user%22%2C%22page%22%2C%22blogpost%22%2C%22attachment%22)&includeArchivedSpaces=false

**Comment by demx8as6** [comment]
**Proposal**

The following counter should be moved from MAC-Interface to EthernetContainer.
The list is filtered from Andreas e[xcel spread sheet](https://wiki.opennetworking.org/download/attachments/265093121/Proposed_Changes_on_PM_Data_for_Ethernet_and_Mac_If_1562021.xlsx?api=v2).


- oversized-frames-ingress
- undersized-frames-ingress
- jabber-frames-ingress
- fragmented-frames-ingress
- frames-of-64-byte
- frames-of-65-to-127-byte
- frames-of-128-to-255-byte
- frames-of-256-to-511-byte
- frames-of-512-to-1023-byte
- frames-of-1024-to-1518-byte
- last-10-sec-frame-input-rate
- total-frames-input
- total-frames-output
- forwarded-frames-input
- forwarded-frames-output
- unicast-frames-input
- unicast-frames-output
- multicast-frames-input
- multicast-frames-output
- broadcast-frames-input
- broadcast-frames-output
- fragmented-frames-input
- errored-frames-input
- errored-frames-output
- dropped-frames-input
- dropped-frames-output
- ifInUnknownProtos

To be approved on 2021-06-30 - 5G xHaul call.

**Comment by openBackhaul** [comment]
Preliminary version
**Decision made on the 5G-xhaul-call on 30th of June 2021:**
The following counters shall be moved from MacInterface to EthernetContainerPerformanceType datatype:
- oversized-frames-ingress
- undersized-frames-ingress
- jabber-frames-ingress
- fragmented-frames-ingress
- last-10-sec-frame-input-rate
- total-frames-input
- total-frames-output
- forwarded-frames-input
- forwarded-frames-output
- unicast-frames-input
- unicast-frames-output
- multicast-frames-input
- multicast-frames-output
- broadcast-frames-input
- broadcast-frames-output
- fragmented-frames-input
- errored-frames-input
- errored-frames-output
- dropped-frames-input
- dropped-frames-output
- ifInUnknownProtos


The following counters shall be moved from MacInterface to EthernetContainerStatus class:
EthernetContainerStatus ::framesOf64Byte : INT64 = -1
EthernetContainerStatus ::framesOf65To127Byte : INT64 = -1
EthernetContainerStatus ::framesOf128To255Byte : INT64 = -1
EthernetContainerStatus ::framesOf256To511Byte : INT64 = -1
EthernetContainerStatus ::framesOf512To1023Byte : INT64 = -1
EthernetContainerStatus ::framesOf1024To1518Byte : INT64 = -1

**Comment by openBackhaul** [comment]
Preliminary version
**Decision made on the 5G-xhaul-call on 30th of June 2021:**
The following counters shall be moved from MacInterface to EthernetContainerPerformanceType datatype:
- oversized-frames-ingress
- undersized-frames-ingress
- jabber-frames-ingress
- fragmented-frames-ingress
- last-10-sec-frame-input-rate
- total-frames-input
- total-frames-output
- forwarded-frames-input
- forwarded-frames-output
- unicast-frames-input
- unicast-frames-output
- multicast-frames-input
- multicast-frames-output
- broadcast-frames-input
- broadcast-frames-output
- fragmented-frames-input
- errored-frames-input
- errored-frames-output
- dropped-frames-input
- dropped-frames-output
- ifInUnknownProtos


The following counters shall be moved from MacInterface to EthernetContainerStatus class:
EthernetContainerStatus ::framesOf64Byte : INT64 = -1
EthernetContainerStatus ::framesOf65To127Byte : INT64 = -1
EthernetContainerStatus ::framesOf128To255Byte : INT64 = -1
EthernetContainerStatus ::framesOf256To511Byte : INT64 = -1
EthernetContainerStatus ::framesOf512To1023Byte : INT64 = -1
EthernetContainerStatus ::framesOf1024To1518Byte : INT64 = -1

**Comment by openBackhaul** [comment]
There is an issue in MacInterface, which is in some sense contradicting:  

`Please delete the following counters from: mac-interface-status:  
frames-of-64-byte  
frames-of-65-to-127-byte  
frames-of-128-to-255-byte
frames-of-256-to-511-byte
frames-of-512-to-1023-byte
frames-of-1024-to-1518-byte`

both have been written at the same day, but this one decided later.

**Comment by openBackhaul** [comment]
Fixed with EthernetContainer_2.0.0-tsp.220405.1755.
