### ISSUE TITLE
min-elements shall be removed from problem-kind-severity-list

### ISSUE THREAD

**Issue by michbin** [openBackhaul/ethernetContainer#46]
As a consequence of removing mandatory alarms from `supported-alarm-list` (see issue #42), the constraint for the minimum number of elements must be removed from **`problem-kind-severity-list`** in `ethernet-container-configuration`. That is, the multiplicity must be changed from 2..* to 0..*.

**Comment by openBackhaul** [comment]
obsoleted by issue #47
